NewStyle/Models/ItemPedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStyle.Models
{
    public class ItemPedido
    {

        public int Id { get; private set; }
        public Produto Produto { get; private set; }
        public int Quantidade { get; private set; }
        public decimal PrecoUnitario { get; private set; }
        public decimal Subtotal
        {
            get
            {
                return Quantidade * PrecoUnitario;
            }
        }

        public ItemPedido(int id, Produto produto, int quantidade) : this (produto, quantidade)
        {
            this.Id = id;
        }


        //Construtor sem id. id é auto incrementavel 
        public ItemPedido(Produto produto, int quantidade)
        {
            this.Produto = produto;
            this.Quantidade = quantidade;
            this.PrecoUnitario = produto.Preco;
        }

        public ItemPedido()
        {

        }

    }
}

NewStyle/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStyle.Models
{
    public class Produto
    {

        public int Id { get; private set; }
        public string Nome { get; private set; }
        public decimal Preco { get; private set; }

        public Produto(int id, string nome, decimal preco) : this(nome, preco)
        {
            this.Id = id;
            
        }

        //Construtor sem id. id é auto incrementavel 

        public Produto()
        {

        }

        public Produto(string nome, decimal preco)
        {
            this.Nome = nome;
            this.Preco = preco;
        }

    }
}

NewStyle/Models/ProdutoMasc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStyle.Models
{
    public class ProdutoMasc
    {
        public int Id { get; private set; }
        public string Nome { get; private set; }
        public decimal Preco { get; private set; }

        public ProdutoMasc (int id, string nome, decimal preco)
        {
            this.Id = id;
            this.Nome = nome;
            this.Preco = preco;
        }

    }
}

NewStyle/Models/ViewModel/CarrinhoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStyle.Models.View_Model
{
    public class CarrinhoViewModel
    {

        public List<ItemPedido> Itens { get; private set; }
        public decimal Total
        {
            get
            {
                return Itens.Sum(i => i.Subtotal);
            }
        }

        public CarrinhoViewModel(List<ItemPedido> itens)
        {
            this.Itens = itens;
        }

    }
}

NewStyle/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NewStyle.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

NewStyle/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using NewStyle.Models;
using NewStyle.Models.View_Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStyle.Controllers
{
    public class PedidoController : Controller
    {

        private readonly IDataService _dataService;
        public PedidoController(IDataService dataService)
        {
            this._dataService = dataService;
        }

        public IActionResult Carrossel()
        {
            List<Produto> produtos = _dataService.GetProdutos();
            return View(produtos);
            //retorna os produtos para o carrossel
        }

        public IActionResult Carrinho()
        {
            CarrinhoViewModel viewModel = GetCarrinhoViewModel();

            return View(viewModel);
        }

        private CarrinhoViewModel GetCarrinhoViewModel()
        {
            //No dataService temos o get de produtos 
            List<Produto> produtos = this._dataService.GetProdutos();
            var itensCarrinho = this._dataService.GetItensPedido();

            CarrinhoViewModel viewModel =
                new CarrinhoViewModel(itensCarrinho);
            return viewModel;
        }

        public IActionResult Resumo()
        {

            CarrinhoViewModel viewModel = GetCarrinhoViewModel();

            return View(viewModel);
        }
    }
}

NewStyle/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

NewStyle/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NewStyle/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

NewStyle/Views/Pedido/Carrinho.cshtml
@{
    ViewData["Title"] = "Carrinho";
}

@model NewStyle.Models.View_Model.CarrinhoViewModel

<h3>Meu Carrinho</h3>

<div class="panel panel-default">

            <!-- Cabeçalho -->
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-6">
                        Item
                    </div>
                    <div class="col-md-2 text-center">
                        Preço Unitário
                    </div>
                    <div class="col-md-2 text-center">
                        Quantidade
                    </div>
                    <div class="col-md-2">
                        <span class="pull-right">
                            Subtotal
                        </span>
                    </div>
                </div>

            </div>

    <!-- Corpo -->
    <div class="panel-body">
        @foreach (var item in Model.Itens)
        {
            <div class="row row-center">
                <div class="col-md-3">
                    <img src="~/images/Produtos/prod0@(item.Id).jpg" />
                </div>
                <div class="col-md-3">@(item.Produto.Nome)</div>
                <div class="col-md-2 text-center">R$ @(item.PrecoUnitario)</div>
                <div class="col-md-2 text-center">@(item.Quantidade)</div>
                <div class="col-md-2">
                    <span class="pull-right">
                        R$ @(item.Subtotal)
                    </span>
                </div>
            </div>
        }
    </div>

    <!-- Rodapé -->
    <div class="panel-footer">
        
        <div class="row">
            <div class="col-md-10">
                <span>Total: @Model.Itens.Count()
                @(Model.Itens.Count() < 2 ? "item" : "itens")</span>
            </div>
            <div class="col-md-2">
                <span class="pull-right">
                    Total: R$ @Model.Total
                </span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <a asp-action="resumo"
               class="btn btn-success pull-right">
                Finalizar Pedido
            </a>

            @*@Html.ActionLink("Finalizar Pedido",
             "resumo",
             "pedido",
             null,
             new { @class = "btn btn-sucess pull-right" })*@
        </div>
    </div>

</div>

NewStyle/Views/Pedido/Carrossel.cshtml
@{
    ViewData["Title"] = "Vitrine";
}

@model List<Produto>

<h3>Vitrine</h3>

<!-- Vitrine feita utilizando o carrossel do bootstrap -->
<div id="my-carousel" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        @*Vitrine*@
        @{
            const int TAMANHO_PAGINA = 4;
            int numPaginas = (int)Math.Ceiling((double)Model.Count() / TAMANHO_PAGINA);
        }
        @for (int pagina = 0; pagina < numPaginas; pagina++)
        {
            <div class="item @(pagina == 0 ? "active" : "")">
                <div class="row">
                    @{
                        var produtosDaPagina = 
                            Model
                            .Skip(TAMANHO_PAGINA * pagina)
                            .Take(TAMANHO_PAGINA);
                    }
                    @foreach (var produto in produtosDaPagina)
                    {
                        <div class="col-md-3">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div align="center"><img src="~/images/Produtos/prod0@(produto.Id).jpg" /></div>
                                </div>
                                <div class="panel-footer">
                                    <div class="text-center">Produto @(produto.Nome)</div>
                                    <div class="text-center">R$ @(produto.Preco)</div>
                                    <div class="text-center">
                                        <a asp-action="carrinho">Adicionar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }


    </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

NewStyle/Views/Pedido/Resumo.cshtml
@{
    ViewData["Title"] = "Resumo";
}
@model NewStyle.Models.View_Model.CarrinhoViewModel

<h3>Resumo do Pedido</h3>

<div class="panel panel-default">
    <div class="panel-body">

        <div class="row">
            <div class="col-md-12">
                <h3>Nº do Pedido: 12345678</h3>
            </div>
        </div>

        <hr />  <!-- Separador horizontal -->

        <div class="row">
            <div class="col-md-3">
                <h3>Seus dados</h3>
                <div>João da Silva</div>
                <div>(11) 1234-5678</div>
            </div>
            <div class="col-md-3">
                joao@gmail.com.br
            </div>
            <div class="col-md-6">
                <h3>Endereço de Entrega</h3>
                <div>Rua Vergueiro, 328 - Vila Mariana - São Paulo - SP</div>
            </div>
        </div>

        <hr />  <!-- Separador horizontal -->
        <div class="row">
            <div class="col-md-10">
                <h3>Item</h3>
            </div>
            <div class="col-md-2">
                <h3>Quantidade</h3>
            </div>
        </div>
        @foreach (var item in Model.Itens)
        {
            <div class="row">
                <div class="col-md-10">
                    <div>@item.Produto.Nome</div>
                </div>
                <div class="col-md-2">
                    <div class="pull-right">@item.Quantidade</div>
                </div>
            </div>
        }



    </div>
</div>

NewStyle/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - New Style</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Pedido" asp-action="Carrossel" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - New Style</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>